import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod-1',
    slug: 'gentle-gel-cleanser',
    name: 'Gentle Gel Cleanser',
    description: 'A mild, pH-balanced cleanser that effectively removes impurities without stripping the skin.',
    ingredients: ['Water', 'Glycerin', 'Green Tea Extract', 'Cocamidopropyl Betaine'],
    howToUse: 'Massage a small amount onto damp skin, lather, and rinse thoroughly. Use morning and night.',
    price: 18.00,
    image: 'prod-cleanser-1',
    brand: 'Savior Skin',
    category: 'cleanser',
    skinTypes: ['oily', 'combination', 'sensitive'],
    skinConcerns: ['acne', 'large pores'],
  },
  {
    id: 'prod-2',
    slug: 'hydrating-rosewater-toner',
    name: 'Hydrating Rosewater Toner',
    description: 'A soothing toner that calms and hydrates the skin, preparing it for subsequent treatments.',
    ingredients: ['Rose Flower Water', 'Glycerin', 'Aloe Vera', 'Witch Hazel'],
    howToUse: 'After cleansing, apply to a cotton pad and gently wipe over the face. Can also be spritzed directly.',
    price: 22.00,
    image: 'prod-toner-1',
    brand: 'Blossom Beauty',
    category: 'toner',
    skinTypes: ['dry', 'sensitive', 'combination'],
    skinConcerns: ['dullness'],
  },
  {
    id: 'prod-3',
    slug: 'vitamin-c-brightening-serum',
    name: 'Vitamin C Brightening Serum',
    description: 'A potent antioxidant serum that brightens skin tone and fights signs of aging.',
    ingredients: ['Water', 'Ascorbic Acid (Vitamin C)', 'Ferulic Acid', 'Hyaluronic Acid'],
    howToUse: 'Apply 2-3 drops to a clean face in the morning before moisturizer and sunscreen.',
    price: 45.00,
    image: 'prod-serum-1',
    brand: 'Savior Skin',
    category: 'serum',
    skinTypes: ['oily', 'dry', 'combination'],
    skinConcerns: ['dullness', 'dark spots', 'aging'],
  },
  {
    id: 'prod-4',
    slug: 'lightweight-daily-moisturizer',
    name: 'Lightweight Daily Moisturizer',
    description: 'A non-greasy moisturizer that provides long-lasting hydration for all skin types.',
    ingredients: ['Water', 'Hyaluronic Acid', 'Ceramides', 'Squalane'],
    howToUse: 'Apply evenly to face and neck as the last step of your routine in the evening, or before sunscreen in the morning.',
    price: 32.00,
    image: 'prod-moisturizer-1',
    brand: 'Savior Skin',
    category: 'moisturizer',
    skinTypes: ['oily', 'dry', 'sensitive', 'combination'],
    skinConcerns: ['acne', 'dullness'],
  },
  {
    id: 'prod-5',
    slug: 'mineral-spf-50-sunscreen',
    name: 'Mineral SPF 50 Sunscreen',
    description: 'A broad-spectrum physical sunscreen that protects against UVA/UVB rays without a white cast.',
    ingredients: ['Zinc Oxide', 'Titanium Dioxide', 'Niacinamide', 'Dimethicone'],
    howToUse: 'Apply liberally 15 minutes before sun exposure. Reapply at least every 2 hours.',
    price: 28.00,
    image: 'prod-sunscreen-1',
    brand: 'Aura Shield',
    category: 'sunscreen',
    skinTypes: ['sensitive', 'oily', 'combination'],
    skinConcerns: ['aging', 'dark spots'],
  },
  {
    id: 'prod-6',
    slug: 'clay-detox-mask',
    name: 'Clay Detox Mask',
    description: 'A purifying clay mask that draws out impurities and minimizes the appearance of pores.',
    ingredients: ['Kaolin Clay', 'Bentonite Clay', 'Charcoal Powder', 'Tea Tree Oil'],
    howToUse: 'Apply an even layer to clean skin, leave on for 10-15 minutes, and rinse with warm water. Use 1-2 times a week.',
    price: 25.00,
    image: 'prod-mask-1',
    brand: 'Savior Skin',
    category: 'mask',
    skinTypes: ['oily', 'combination'],
    skinConcerns: ['acne', 'large pores'],
  },
  {
    id: 'prod-7',
    slug: 'balancing-face-oil',
    name: 'Balancing Face Oil',
    description: 'A nourishing blend of oils that helps to balance sebum production and soothe inflammation.',
    ingredients: ['Jojoba Oil', 'Rosehip Oil', 'Squalane', 'Vitamin E'],
    howToUse: 'Warm a few drops between your palms and press gently into the skin as the last step of your routine.',
    price: 38.00,
    image: 'prod-oil-1',
    brand: 'Blossom Beauty',
    category: 'face oil',
    skinTypes: ['dry', 'combination'],
    skinConcerns: ['dullness', 'aging'],
  },
  {
    id: 'prod-8',
    slug: 'aha-bha-exfoliating-solution',
    name: 'AHA/BHA Exfoliating Solution',
    description: 'A chemical exfoliant that smooths skin texture and clears congested pores.',
    ingredients: ['Glycolic Acid (AHA)', 'Salicylic Acid (BHA)', 'Lactic Acid', 'Glycerin'],
    howToUse: 'Use 2-3 times per week at night on clean, dry skin. Do not rinse. Follow with a moisturizer.',
    price: 35.00,
    image: 'prod-exfoliant-1',
    brand: 'Savior Skin',
    category: 'exfoliant',
    skinTypes: ['oily', 'combination'],
    skinConcerns: ['acne', 'dullness', 'large pores'],
  },
  {
    id: 'prod-9',
    slug: 'caffeine-eye-cream',
    name: 'Caffeine Eye Cream',
    description: 'An energizing eye cream that reduces puffiness and diminishes dark circles.',
    ingredients: ['Water', 'Caffeine', 'Peptides', 'Hyaluronic Acid'],
    howToUse: 'Gently tap a small amount around the eye area with your ring finger.',
    price: 30.00,
    image: 'prod-eyecream-1',
    brand: 'Aura Shield',
    category: 'eye cream',
    skinTypes: ['oily', 'dry', 'sensitive', 'combination'],
    skinConcerns: ['aging', 'dark spots'],
  },
  {
    id: 'prod-10',
    slug: 'salicylic-acid-spot-treatment',
    name: 'Salicylic Acid Spot Treatment',
    description: 'A targeted treatment to quickly reduce the size and redness of blemishes.',
    ingredients: ['Salicylic Acid', 'Witch Hazel', 'Tea Tree Oil', 'Niacinamide'],
    howToUse: 'Apply a thin layer directly onto blemishes one to three times daily.',
    price: 15.00,
    image: 'prod-acne-1',
    brand: 'Savior Skin',
    category: 'serum',
    skinTypes: ['oily', 'combination'],
    skinConcerns: ['acne'],
  },
  {
    id: 'prod-11',
    slug: 'retinol-night-serum',
    name: 'Retinol Night Serum',
    description: 'A powerful serum that accelerates skin renewal to reduce fine lines, wrinkles, and texture.',
    ingredients: ['Retinol', 'Squalane', 'Bisabolol', 'Jojoba Oil'],
    howToUse: 'Apply a pea-sized amount at night, starting with 1-2 times per week and gradually increasing frequency.',
    price: 55.00,
    image: 'prod-antiaging-1',
    brand: 'Aura Shield',
    category: 'serum',
    skinTypes: ['oily', 'dry', 'combination'],
    skinConcerns: ['aging', 'dark spots', 'dullness'],
  },
  {
    id: 'prod-12',
    slug: 'hyaluronic-acid-serum',
    name: 'Hyaluronic Acid Serum',
    description: 'An intensely hydrating serum that plumps the skin and reduces the appearance of fine lines.',
    ingredients: ['Water', 'Sodium Hyaluronate', 'Glycerin', 'Panthenol'],
    howToUse: 'Apply a few drops to damp skin morning and night before creams.',
    price: 28.00,
    image: 'prod-hydrating-serum-1',
    brand: 'Blossom Beauty',
    category: 'serum',
    skinTypes: ['dry', 'sensitive', 'oily', 'combination'],
    skinConcerns: ['dullness', 'aging'],
  },
];
